add films to main screen
htmlacademy-react/423857-what-to-watch-6 pull request #10
Opened 2021-02-23 08:19 UTC by kolo-ky

2021-02-23 11:49 UTC, Razzwan requested changes

2021-02-23 11:49 UTC, Razzwan commented on src/components/app/app.jsx
> +  });
Должен быть второй парамент с зависимостями, в которых должен быть аргумент `loadMovies`  вот так:
```jsx
  useEffect(() => {
    loadMovies();
  }, [loadMovies]);
```

2021-02-23 11:49 UTC, Razzwan commented on src/components/genre-list/genre-list.jsx
> +  genres.unshift({
Не лучшая идея, т.к. это мутация. Можем обсудить альтернативные варианты. Один из них:
```jsx
const preparedGenres = [
  { 
    title: `All categories`,
    value: null,
  },
  ...genres,
];
```
Но еще лучше эти данные подготовить в селекторах

2021-02-23 11:49 UTC, Razzwan commented on src/components/genre-list/genre-list.jsx
> +  genres = Array.from(new Set(genres.map(JSON.stringify))).map(JSON.parse);
Такой код лучше писать в селекторах. Можно существенно упростить и улучшить при этом производительность

2021-02-23 11:49 UTC, Razzwan commented on src/components/genre-list/genre-list.jsx
> +    changeGenre: (value) => dispatch(changeGenreAction(value)),
Напомни мне, чтоб я объяснил вот этот синтаксис и мы обсудили, почему это лучши и какие он накладывает ограничения:
```jsx
const mapDispatchToProps = {
  changeGenreAction,
};
```

2021-02-23 11:49 UTC, Razzwan commented on src/components/movie-card-list/movie-card-list-proxy/movie-card-list-proxy.jsx
> +  const [count, updateCount] = useState(NUMBER_OF_FILMS);
Принято второй аргумент называть `setCount`. 
1. Это короче
2. `update` чаще используется для более сложного процесса обновления данных, хотя, возможно, это субъективно

2021-02-23 11:49 UTC, Razzwan commented on src/components/movie-card-list/movie-card-list-proxy/movie-card-list-proxy.jsx
> +    updateCount((prevState) => prevState * 2);
Сомневаюсь, что это будет работать достаточно хорошо. Получается геометрическая прогрессия. Лучше записать так:
```jsx
const handleClick = useCallback(() => {
    updateCount((prevState) => prevState + NUMBER_OF_FILMS);
}, [updateCount]);
```

2021-02-23 11:49 UTC, Razzwan commented on src/components/movie-card-list/movie-card-list-proxy/movie-card-list-proxy.jsx
> +        filmsCount > count
Лучше записать так:
```jsx
{filmsCount > count && (
  <ShowMore sendClick={handleClick} />
)}
```

2021-02-23 11:49 UTC, Razzwan commented on src/components/movie-card-list/movie-card-list-proxy/movie-card-list-proxy.jsx
> +    changeGenre: (genre) => dispatch(changeGenreAction(genre)),
Тоже лучше писать вот так:
```jsx
const mapDispatchToProps = {
  changeGenreAction,
};
```
1. Короче
2. Устраняет возможность написать сложную логику в момент импорта экшена в компонент, что улучшает читаемость и структуру кода.

2021-02-23 11:49 UTC, Razzwan commented on src/components/movie-card-list/movie-card-list-proxy/selector.js
> +      return state.films.filter((film) => film.genre === state.genre).slice(0, count);
Лучше испльзовать селекторы. Можем обсудить или сам погугли

2021-02-23 11:49 UTC, Razzwan commented on src/components/screens/main/main.jsx
> +    let genres = films.map((film) => {
1. Лучше использовать селекторы
2. Данные не должны браться из фильмов (по крайней мере, не для всех случаев). Лучше вручную создать массив с категориями

2021-02-23 11:49 UTC, Razzwan commented on src/components/screens/main/main.jsx
> +  isFilmsAvailable: state.films.length > 0,
Лучше использовать селекторы

2021-02-23 11:49 UTC, Razzwan commented on src/components/screens/my-list/my-list.jsx
> +  return null;
Это лучше написать в начале, чтоб основная часть компонента возрващалась по-умолчанию без условий:
```jsx
if (! isFilmsAvailable) {
  return null;
}

return (
  <div>{* Основная часть JSX разметки компонента *}</div>
);
```

2021-02-23 11:49 UTC, Razzwan commented on src/components/screens/my-list/my-list.jsx
> +  films: state.films.filter((film) => film.is_favorite)
Селекторы

2021-02-23 11:49 UTC, Razzwan commented on src/store/enhancers.js
> +export const getMovies = () => (next, _getState) => {
Почему `next`? Это `dispatch`. Хотя идея называть это next интересная. Можем обсудить

2021-02-23 11:49 UTC, Razzwan commented on src/store/reducer.js
> +    case SET_LOADING:
SET_LOADING лучше переименовать в `TOGGLE_LOADING`

2021-02-23 11:49 UTC, Razzwan commented on src/types/film-types.js
> +  "id": PropTypes.number.isRequired,
1. Кавычки, похоже, лишние.
2. Название файла содержит множественное число, но в файле тим одного фильма, т.е. `film-type`

2021-02-24 04:55 UTC, kolo-ky commented on src/components/app/app.jsx
> +  });
Сделал, но не понял, зачем. Мы же это действие выполняем один раз, при старте приложения.

2021-02-24 05:08 UTC, kolo-ky commented on src/store/enhancers.js
> +export const getMovies = () => (next, _getState) => {
так нам показали

2021-02-24 05:11 UTC, kolo-ky commented on src/types/film-types.js
> +  "id": PropTypes.number.isRequired,
там через землю, линт ругается, а данные именно с землей с сервера приходят

2021-02-24 05:41 UTC, Razzwan approved these changes

2021-02-24 05:41 UTC, merged